version: '3.7'

services:
## PG
  book-db:
    container_name: books-db-dev
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.db-dev.env
    ports:
    - "5433:5432"

## Flask App
  book-app:
    container_name: books-app-dev
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    volumes:
      - './app/src/:/src/'
    ports:
      - 5003:5000
    depends_on:
      - book-db
    links:
      - book-db

volumes:
  postgres_data:
